// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://isqnxsypldpedqcbzqgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzcW54c3lwbGRwZWRxY2J6cWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NTgzOTAsImV4cCI6MjA2MDQzNDM5MH0.NXdG5OKnBChxN1Mm_WYY7yizCBXsao2MWeuQ44ODkqA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);